on:
  pull_request:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20.0'

      - name: Build image
        run: docker build . --file Dockerfile
